### ISSUE TITLE
Add support for mlocked memory

### ISSUE THREAD

**Issue by rblaze** [vincenthz/hs-memory#28]
One of the uses of ByteArray is to store crypto keys in in the cryptonite package. It would be great to add another ByteArray instance, LockedArray, which allocates the chunk of foreign memory and mlock()'s it, then scrubs and unlocks it in destructor.

**Comment by vincenthz** [comment]
If anyone want to add this, then I'm all for it but it's quite fiddly to have something that works reliably:

* up until "recently" mlock was still a priviledge user only business, so the compat is annoying.
* It's easy to waste quite lots of memory with a naive design since mlock doesn't work at the byte level but only on pages/mapping. 

That said I'm not planning to add this myself, because I think the encrypted swap solution is largely superior, and more user friendly. Sadly the big caveat is that it requires to have encrypted swap configured which we can't really detect ahead of time, which leave the user SOL.

**Comment by vincenthz** [comment]
I took the liberty to clarify the title of the issue, let me know if it's mis-characterized.

**Comment by rblaze** [comment]
I think I'll try to implement it "some time soon". My guess at design is to have a set of locked-memory pools, each serving power-of-2 sized chunks, and grab a chunk from the closest higher size. This will limit max chunk size to page size, but I don't expect it being a problem, sensitive data are rarely that big.

As for compatibility with older kernels and ulimits, my idea is to return additional flag signaling if chunk was actually locked or not, and let application handle this.

**Comment by vincenthz** [comment]
closing this as no one has time to do this and keeping the issue tracker without wishlist feature
