### ISSUE TITLE
memory-0.14.12 fails to compile on GHC-7.8.4

### ISSUE THREAD

**Issue by phadej** [vincenthz/hs-memory#44]
This breaks servant-mock CI build: https://travis-ci.org/haskell-servant/servant-mock/jobs/329060789
https://github.com/haskell-servant/servant-mock/pull/14

```
[21 of 28] Compiling Data.ByteArray.Methods ( Data/ByteArray/Methods.hs, dist/build/Data/ByteArray/Methods.o )
Data/ByteArray/Methods.hs:303:1:
    No instance for (ByteArray (SPE.Block Word8))
      arising from a specialisation pragma for ‘convert’
    In the SPECIALISE pragma
      {-# SPECIALIZE convert :: SPE.ByteString -> SPE.Block Word8 #-}
Data/ByteArray/Methods.hs:305:1:
    No instance for (ByteArrayAccess (SPE.Block Word8))
      arising from a specialisation pragma for ‘convert’
    In the SPECIALISE pragma
      {-# SPECIALIZE convert :: SPE.Block Word8 -> SPE.ByteString #-}
cabal: Failed to build memory-0.14.12 (which is required by
servant-server-0.12). See the build log above for details.
```

**Comment by RyanGlScott** [comment]
Hm... I want to try and fix this, since it's causing problems for me too. (see [this Travis build](https://travis-ci.org/ku-fpg/kansas-comet/jobs/329605742#L873)). But I can't even find the offending lines in the repo! When I checkout `memory-0.14.12` from Hackage, I can see these lines at the end of `Data.ByteArray.Methods`:

```
#if defined(WITH_BYTESTRING_SUPPORT) && defined(WITH_FOUNDATION_SUPPORT)
{-# SPECIALIZE convert :: SPE.ByteString -> SPE.UArray Word8 #-}
{-# SPECIALIZE convert :: SPE.ByteString -> SPE.Block Word8 #-}
{-# SPECIALIZE convert :: SPE.UArray Word8 -> SPE.ByteString #-}
{-# SPECIALIZE convert :: SPE.Block Word8 -> SPE.ByteString #-}
#endif
```

But those lines are nowhere to be seen [here](https://github.com/vincenthz/hs-memory/commit/735d696aa53db543a06461c625578ab6bc64c880#diff-3baf4eb2e17a7e89c92c985042533638R293). What gives?

**Comment by ocheron** [comment]
It seems branch basement-optimisation is the new master.

**Comment by vincenthz** [comment]
@RyanGlScott thanks for raising your comment, there was couple of mistake at the release process (sdist from wrong branch as @ocheron mentioned, and unpushed commits/tag). it should be fixed now with `.13`

**Comment by RyanGlScott** [comment]
Wonderful, thanks! `memory-0.14.13` works like a charm.

**Comment by phadej** [comment]
@vincenthz Could you or should I (as Hackage Trustee) revise `memory-0.14.12` with `base >= 4.8` lower bound, so it won't be picked into any install plans?
