### ISSUE TITLE
Get slice of ByteString

### ISSUE THREAD

**Issue by flip111** [vincenthz/hs-memory#78]
Is there a way to get a slice into an already existing `ByteString` (or a type that implements `ByteArrayAccess`)? It looked like [View](https://hackage.haskell.org/package/memory-0.15.0/docs/Data-ByteArray.html#v:view) could do it, but i have been unable to use this data constructor. It would be best to just get a new `ByteString` without the `View` constructor. I realize that this is potentially dangerous when the `ByteString` viewed into gets de-allocated. But it would be nice for a low level interface when offsets into the `ByteString` get returned.

**Comment by ocheron** [comment]
What you ask is already covered by the API in `Data.ByteString`: functions like `drop` and `take` there all return an output value sharing the underlying buffer of the input value. That's why there is a `copy` function to counter it.

`View` is also possible but the constructor is not exposed, you have to use functions like `view`, `takeView`, `dropView`.

All of that manage the retention and should not be dangerous.
